### ISSUE TITLE
Missing prefabs on TestScene

### ISSUE THREAD

**Issue by Maciej92Zareba** [studentutu/Tilia.UnityUI#3]
So i downloaded Talia Unity.UI package and followed read me to download necessary packages and when i open "TestScene" a lot of prefabs are missing. 
![obraz](https://user-images.githubusercontent.com/46682105/157483766-db58dad7-6ab2-4445-8617-ad1a461cbbd5.png)

**Comment by studentutu** [comment]
working on it, I will also update Readme.md

**Comment by studentutu** [comment]
@Maciej92Zareba  fixed it in v 1.7.0
