### ISSUE TITLE
Does this support touch interaction?

### ISSUE THREAD

**Issue by JamesSozoLabs** [studentutu/Tilia.UnityUI#8]
Hey,

I need the user to be able to either user the pointer for UIs in the distance, but touch for UIs nearby.
Does this package support touch interactions?

**Comment by studentutu** [comment]
Yes, it should - use VRTK Canvas with collision enabling - there is a documentation for it in an old VRTK 3.3 version, should as is in with VRTK 4.0

**Comment by JamesSozoLabs** [comment]
Awesome, thank you so much.
I've been overcomplicating it too much.

**Comment by wizVR-zhangjun** [comment]
@studentutu @JamesSozoLabs  
I want to implement a response to UI events with finger touch, but I don't know how to do it and haven't found a good example. Could you please give me some suggestions? Wish you good health and a happy work experience
